config/urls.py
from django.contrib import admin
from django.urls import path, include

from explorea.events import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.index, name='index'), # path vraci objekt URLPattern <URLPattern "..nejaky regularni vyraz.." [name=".."]>
    path('', views.IndexView.as_view(), name='index'),
    path('events/', include('explorea.events.urls', namespace="events")), #nyni muzeme v templatech referencovat url jako {% url "namespace:name" "var"%}, takze ruzne aplikace mohou mit stejne name (myapp/urls.py path(...,name=...))
    path('accounts/', include('explorea.accounts.urls', namespace="accounts")),
    path('cart/', include('explorea.cart.urls', namespace='cart')),
    path('posts/', include('explorea.posts.urls', namespace='posts')),
]


if settings.DEBUG: # pokud je pouzit testovaci Django server - pri ostrem provozu se pouziva k obsluhovani images separatni nezavisly server
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # static funkce spoji obe casti cesty v jeden celek (vraci list objektu URLPattern <URLPattern "..nejaky regularni vyraz.."> )

explorea/accounts/urls.py
from django.urls import path
from django.conf.urls import url

from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts' #to se propoji s config.urls kde je definovan namespace=...

urlpatterns = [
    #path('profile/', views.profile, name='profile'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    #path('login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    #path('logout/', auth_views.LogoutView.as_view(template_name="accounts/logged_out.html"), name='logout')
    path('logout/', auth_views.LogoutView.as_view(next_page="/events/all/"), name='logout'),
    #path('register/', views.register, name='register'),
    path('register/', views.RegisterView.as_view(), name='register'),
    #path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),

    #path('hosts/', views.host_list, name='host_list'),
    path('hosts/', views.HostListView.as_view(), name='host_list'),
    #path('become-host/', views.become_host, name='become_host'),
    path('become-host/', views.BecomeHostView.as_view(), name='become_host'),
    #path('host/profile/<username>/', views.host_profile, name='host_profile'),
    path('host/profile/<username>/', views.HostProfileView.as_view(), name='host_profile'),
    #url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.activate_host, name='activate_host'),
    url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.ActivateHostView.as_view(), name='activate_host'),

    # <uidb64> a <token> se zparsuji do views.activate_host jako kwargs;
    # ?P<uidb64> je Python named capture group (<uidb64> je refernece na [0-9A-Za-z]+, muze byt backreferencovana jako (?P=uidb64)), . = libovolny znak

    #path('change-password/', views.change_password, name='change_password'),
    path('change-password/', views.PasswordChangeView.as_view(), name='change_password'),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name = 'accounts/reset_password.html', email_template_name='accounts/reset_password_email.html'),
        name='reset_password'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    # path('ajax/validate_username/', views.ValidateUsernameView.as_view(), name='validate_username'),
    path('ajax/validate_exists/', views.ValidateRegisterFormView.as_view(), name='validate_register_form'), # nahrazuje predchozi path

    ]

explorea/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='detail'),
    path('add/<slug:slug>/', views.CartAddView.as_view(), name='add'),
    #path('remove/<product_id>/', views.CartRemoveView.as_view(), name='remove'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),

]

explorea/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    #path('new/', views.add_event, name='add_event'),
    path('new/', views.AddEventView.as_view(), name='add_event'),
    #path('mine/', views.my_events_listing, name='my_events_listing'),
    path('mine/', views.MyEventsView.as_view(), name='my_events_listing'),
    #path('search/', views.event_search, name='search'),
    path('search/', views.EventSearchView.as_view(), name='search'),

    #path('detail/<slug:slug>/', views.event_detail, name='event_detail'),#slug je samostatny type (jako str nebo int)
    path('detail/<slug:slug>/', views.EventDetailView.as_view(), name='event_detail'),
    #path('update/<slug:slug>/', views.update_event, name='update_event'),#chybejici lomitko na konci nesmyslne spousti nasledujici pattern!
    path('update/<slug:slug>/', views.UpdateEventView.as_view(), name='update_event'),
    #path('delete/<slug:slug>/', views.delete_event, name='delete_event'),
    path('delete/<slug:slug>/', views.DeleteEventView.as_view(), name='delete_event'),

    #path('<slug:slug>/update_run/<str:run_id>/', views.update_run, name='update_run'),
    path('<slug:slug>/update_run/<str:run_id>/', views.UpdateEventRunView.as_view(), name='update_run'),
    #path('<slug:slug>/delete_run/<str:run_id>/', views.delete_run, name='delete_run'),
    path('<slug:slug>/delete_run/<str:run_id>/', views.DeleteEventRunView.as_view(), name='delete_run'),
    #path('<slug:slug>/add_run/', views.add_run, name='add_run'),
    path('<slug:slug>/add_run/', views.AddEventRunView.as_view(), name='add_run'),

    #path('<str:event_id>/runs/', views.runs_listing, name='runs_listing'),
    #path('<str:event_id>/<str:run_id>/', views.run_detail, name='run_detail'),

    #path('<category>/', views.events_listing, name='events_listing'),
    path('<category>/', views.EventListView.as_view(), name='events_listing'),

]

explorea/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('<slug:slug>/add_rating/', views.AddRatingView.as_view(), name='add_rating'),
    path('<slug:slug>/ratings/', views.RatingListView.as_view(), name='ratings_listing'),
]

explorea/cart/models.py
from django.db import models

# Create your models here.

explorea/posts/forms.py
from django import forms

from explorea.events.models import EventRun
from . models import Rating

from django.forms import ModelChoiceField

class MyModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return str(obj.date) + " " + str(obj.time)

class AddRatingForm(forms.ModelForm):

    # implement MyModelChoiceField
    eventrun = MyModelChoiceField(queryset = EventRun.objects.all(), empty_label=None)

    class Meta:
        model = Rating
        exclude = ["event"]

explorea/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, update_session_auth_hash, get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse

# from django.contrib.auth.mixins import LoginRequiredMixin # LoginRequiredMixin byl z dedicnosti odstranen po zavedeni custom middleware
from django.views.generic import TemplateView, DetailView, ListView, View
from django.views.generic.base import TemplateResponseMixin, ContextMixin
from django.views.generic.edit import CreateView, UpdateView, FormMixin, ProcessFormView
from django.urls import reverse_lazy

from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes

from .forms import RegisterForm, EditUserForm, EditProfileForm
from .models import Profile

UserModel = get_user_model()
token_generator = PasswordResetTokenGenerator()


# @login_required
#
# def profile(request):
#
#     return render(request, 'accounts/profile.html')


class ProfileView(TemplateView):

    template_name = 'accounts/profile.html'


# def register(request):
#
#     if request.method == 'POST':
#
#         # create the form and populate it with data from the POST request
#         form = RegisterForm(request.POST)
#
#         # validate the data in the form
#         if form.is_valid():#vytvoren atribut form.cleaned_data (type=dict) a validovana data do nej ulozena
#
#
#             # get the validated data from the form
#             username = form.cleaned_data.get('username')# nazvy poli formulare jsou ve slovniku jako "key" (type=str)
#             email = form.cleaned_data.get('email')
#             first_name = form.cleaned_data.get('first_name')
#             last_name = form.cleaned_data.get('last_name')
#             password = form.cleaned_data.get('password1')
#
#             # create and save the user
#             User = get_user_model() # ziska referenci k nami zvolenemu user modelu (settings.AUTH_USER_MODEL, nachazi se v general_settings.py a Djanguv defaultni je auth.User)
#             u = User(username=username,
#                      email=email,
#                      first_name=first_name,
#                      last_name=last_name)
#             u.set_password(password)#pouze tato metoda ulozi password hash
#             u.save()
#
#             # get the validated data from the form, create and save the user
#             user=form.save()# protoze implementujeme RegisterForm jako ModelForm--> lze pouzit save --> vrati user object jako radek, ktery zapise do databaze
#             raw_password = form.cleaned_data.get('password1')
#
#             #user = authenticate(username=username, password=password) #vyhleda username v databazi, zahashuje argument password a porovna s odpovidajicim v databazi, vrati objekt user
#             user = authenticate(username=user.username, password=raw_password)
#             login(request, user) #vytvori user session
#
#             # redirect to another page
#             return redirect('accounts:profile')#parametrem je view, ktery chceme spustit, Django default - settings.LOGIN_REDIRECT_URL (="/accounts/profile")
#
#         else: # form.is_valid() vrati False, viz def change_password
#             return render(request, 'accounts/register.html', {'form': form} )
#
#     # if the request is of type GET
#     form = RegisterForm()
#     return render(request, 'accounts/register.html', {'form': form} )


class RegisterView (CreateView):
    model = UserModel
    form_class = RegisterForm
    template_name = 'accounts/register.html'

    #success_message = 'The user %(username)s has been registered successfully' # property pouzivane MessageActionMixin metodami
    #error_message = 'The user %(username)s can not be registered'

    def form_valid(self, form):
        user = form.save()
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=user.username, password=raw_password)
        login(self.request, user)

        #super().form_valid(form)

        return redirect('accounts:profile')


# @login_required
# def edit_profile(request):
#
#     user_form = EditUserForm(request.POST or None, instance=request.user) #  pokud request.method == 'GET': request.POST je <QueryDict {}>, pokud request.method == 'POST': request.POST je <QueryDict {"csrfmiddlewaretoken": ["..."], "username":["Michal"], ..., "about":["neco"]}>
#     profile_form = EditProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)#instance urcuje jaka data maji byt ve formulari predvyplnena # musi byt dodrzene poradi requestu text, files
#                                                                                                             #  pokud request.method == 'POST', request.POST nyni obsahuje field: "avatar":["nazev_obrazku.png"]
#     if request.method == 'POST':
#
#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()
#             profile = profile_form.save()
#
#             request.session['profile_changes'] = request.session.setdefault('profile_changes', 0) + 1#do request.session objektu (lze s nim pracovat jako se slovnikem) se ulozi pod klicem profile_changes defautni hodnota 0,
#                                                                                    #ktera se pri kazdem ulozeni formulare do databaze ve views.edit_profile zvysi o 1
#             return redirect('accounts:profile')
#
#     return render(request, 'accounts/edit_profile.html',
#         {'user_form': user_form, 'profile_form': profile_form})


class MultipleFormsMixin (ContextMixin):
    forms_classes = {}
    initial = {}
    success_url = "" # atributy budou overridovany view, ktere z mixinu dedi

    def get_forms_classes (self):

        return self.forms_classes.copy() # copy() - puvodni dict forms_classes zustane nezmenen v pripade, ze se zmeni novy dict (ktery vraci get_forms_classes()), jinak by se pripadne zmeny dotkly obou
                                        # vezme to, co je definovano v EditProfileView.forms_classes a pokracuje v MFM.get_forms(): forms = self.get_forms_classes()
    def get_context_data(self, **kwargs):

        if 'forms' not in kwargs:
            forms = self.get_forms() # GET: forms = {'user_form': <EditUserForm bound=False, valid=Unknown, fields=(username;email;first_name;last_name;password)>, 'profile_form': <EditProfileForm bound=False, valid=Unknown, fields=(about;avatar)>}

            for name, form in forms.items():
                kwargs[name] = form # ulozi napr. kwargs["user_form"]= <EditUserForm bound=False, valid=Unknown, fields=(username;email;first_name;last_name;password)>
                                    # ve vysledku kwargs==forms

            return super().get_context_data(**kwargs) # ContextMixin.get_context_data()


#        else:
#            keys = ("user_form", "profile_form")
#            for index,value in enumerate(kwargs["forms"]):
#                kwargs[keys[index]]=value
#            kwargs.pop ("forms")


    def get_forms_kwargs(self):
        kwargs = {}
        for name, form in self.forms_classes.items():
            kwargs[name] = {"initial": self.get_initial(),}
            if self.request.method in ('POST', 'PUT'):
                kwargs[name].update({'data': self.request.POST, 'files': self.request.FILES,})

        return kwargs

    def get_forms(self, forms_classes = None):
        if forms_classes is None:
            forms = self.get_forms_classes() # GET, POST: forms = {'user_form': <class 'explorea.accounts.forms.EditUserForm'>, 'profile_form': <class 'explorea.accounts.forms.EditProfileForm'>}

        kwargs = self.get_forms_kwargs() # GET: kwargs = {'user_form': {'initial': {}, 'instance': <SimpleLazyObject: <User: ab>>}, 'profile_form': {'initial': {}, 'instance': <Profile: Profile object (1)>}}
                                        # POST: kwargs = {'user_form': {'initial': {}, 'data': <QueryDict: {'csrfmiddlewaretoken': ['..'], 'username': ['ab'], 'email': ['a@b.cz'], 'first_name': ['Acko'], 'last_name': ['Becko'], 'about': ['dwdwd']}>, 'files': <MultiValueDict: {'avatar': [<InMemoryUploadedFile: ..>]}>, 'instance': <SimpleLazyObject: <User: ab>>},
                                        #              'profile_form': {'initial': {}, 'data': <QueryDict: {'csrfmiddlewaretoken': ['..'], 'username': ['ab'], 'email': ['a@b.cz'], 'first_name': ['Acko'], 'last_name': ['Becko'], 'about': ['dwdwd']}>, 'files': <MultiValueDict: {'avatar': [<InMemoryUploadedFile: ..>]}>, 'instance': <Profile: Profile object (1)>}}
                                        # odkazuje na EditProfileView.get_forms_kwargs()

        return {name:form(**kwargs[name]) for name, form in forms.items()} # dict.items() vraci [("key", value), ("key", value), ... ], **dict - rozbali pary key:value jako kwargs (var=value) pri volani funkce
                                                                        # napr. pro 'user_form' vraci:
                                                                        #    GET: forms['user_form'](**kwargs['user_form']) --> <EditUserForm bound=False, valid=Unknown, fields=(username;email;first_name;last_name;password)>

explorea/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'>

    {% csrf_token %}

<!--{{ form.errors }} django default vypis erroru -->
<!--{{ form.as_p }} django default formular
oboji nahrazeno custom stylem -->

{% for field in form.visible_fields %} <!--fields, ktere nejsou type=hidden -->

    {% for error in field.errors %} <!--{{ form.errors }} django default vypis erroru -->
      {{ error }}
    {% endfor %}  <!--zobrazi vzdy posledni zaznamenany error, vzdy nad polem, ktereho se tyka -->

    <p>{{ field.label_tag}}{{ field }}</p>
{% endfor %}

    <input type="submit" value="Change">

</form>

{% endblock content %}

explorea/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block title %}
<title>Profile</title>
{% endblock title %}

{% block content %}
<div>

  <h2>Edit your profile</h2>
<!--chceme vlastni sablonu pro views.edit_profile-->

  <form method="post" enctype="multipart/form-data">

    {% csrf_token %}

<!--
    <p>{{ form.username.label }}: {{ form.username }}</p>
    <p>{{ form.email.label }}: {{ form.email }}</p>
    <p>{{ form.first_name.label }}: {{ form.first_name }}</p>
    <p>{{ form.last_name.label }}: {{ form.last_name }}</p>
-->

    {% for field in user_form.visible_fields %}

        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        {% if field.label != "Password" %}
        <p>{{ field.label_tag}}{{ field }}</p>
        {% endif %}

    {% endfor %}

    {% for field in profile_form.visible_fields %}

        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}}{{ field }}</p>

    {% endfor %}

    <p>Profile changes: {{ request.session.profile_changes }}</p>

    <button type="submit">Save</button>
  </form>

</div>
{% endblock content %}

explorea/templates/accounts/host_list.html
{% extends 'base.html' %}
{% load accounts_tags %}
{% load static %}


{% block title %}
<title>Host list</title>
{% endblock title %}

{% block content %}

{% for profile in profiles %}
<div>
    <a href="{{ profile.get_absolute_url }}">
        <p>{{ profile.user.username }}</p>
    </a>
        <p> {% if profile.avatar|has:'url' %} <!--zmeneno z user.profile.avatar -->
        <img src="{{ profile.avatar.url }}" alt='{{ profile.user.username }}'> <!--zmeneno z user.profile.avatar.url - chceme zobrazit avatar hostitelu, ne vlastni-->
    {% else %}  <!-- alt - alternativni text pro pripad ze obrazek nemuze byt zobrazen, zobrazi se vedle obrazku -->
        <img src="{% static 'img/avatar.jpg' %}" alt='Not Available'>
    {% endif %}
        </p>
</div>

{% empty %} <!--v pripade, ze profiles je prazdny; musi byt uvnitr for cyklu; for - empty - endfor == if -- for - endfor -- else -- endif -->
    {% if user|has:'profile' and user.profile.is_host %}
        <p>You are the only host right now</p>
    {% else %}
        <p>No hosts right now</p>
    {% endif %}
{% endfor %}

{% if user|has:'profile' and not user.profile.is_host %}
<div>
    <a href="{% url 'accounts:become_host' %}">Become a host</a>
</div>
{% endif %}

{% endblock content %}

explorea/templates/accounts/host_profile.html
{% extends 'base.html' %}
{% load static %}
{% load accounts_tags %}

{% block content %}

<br>
<table>
    <tr>
        <td>
        {% if  host.profile.avatar|has:'url' %}
            <img src="{{ host.profile.avatar.url }}">
        {% else %}
            <img src="{% static 'img/avatar.jpg' %}">
        {% endif %}
        </td>

    </tr>
    <tr>
        <td>hostname: </td><td>{{ host.hostname }}</td>
    </tr>
    <tr>
        <td>First Name: </td><td>{{ host.first_name }}</td>
    </tr>
    <tr>
        <td>Last Name: </td><td>{{ host.last_name }}</td>
    </tr>
    <tr>
        <td>Email: </td><td>{{ host.email }}</td>
    </tr>
    <tr>
        <td>Joined: </td><td>{{ host.date_joined }}</td>
    </tr>
    <tr>
        <td>About Me: </td><td>{{ host.profile.about }}</td>
    </tr>
</table>

{% endblock content %}

explorea/templates/accounts/host_verification_email.html
<p>Dear {{ user.username }}</p>

<p>You are one step from becoming host at Explorea. Please click the below link button to complete the verification:</p>

<a href="http://{{ domain }}{% url 'accounts:activate_host' uidb64 token %}" target="_blank">Verify</a>    <!-- target="_blank": otevre odkaz v novem okne/karte -->


<p>Thanks for using our site!</p>

<p>The Explorea team</p>

explorea/templates/accounts/invalid_link.html
{% extends 'base.html' %}

{% block title %}
<title>Link invalid</title>
{% endblock title %}

{% block content %}
<p>Unfortunately we were not able to perform the verification. Is it possible that your link is older than 7 days?</p>

<p><a href="{% url 'accounts:become_host' %}">Apply again</a></p>
{% endblock content %}

explorea/templates/accounts/logged_out.html
{% extends 'base.html' %}

{% block content %}
<h2>Ciao</h2>

<p>You have been logged out. But if you decide to log in again, we will be happy to see you here.</p>

{% endblock content %}

explorea/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>Login</title>{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock css %}

{% block content %}

<main>

  <div class="main-banner" id="main-banner-small">
  </div>

  <div class="login-register">
    <h2>Login</h2>

    <form method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}}{{ field }}</p>

    {% endfor %}
        <button type="submit" class="submit-button">Log in</button>
    </form>

  </div>

</main>

{% endblock %}

explorea/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load accounts_tags %}  <!--aby se spravne naloadoval modul accounts_tags z package templatetags, je potreba restart serveru -->

{% block title %}
<title>Profile</title>
{% endblock title %}

{% block content %}
<br>
<table>
  <tr>
      <td>

      {% if user.profile.avatar|has:'url' %}
          <img src="{{ user.profile.avatar.url }}">
      {% else %}
          <img src="{% static 'img/avatar.jpg' %}">
      {% endif %}

      </td>
  </tr>

    <tr>
        <td>Username: </td><td>{{ user.username }}</td>
    </tr>
    <tr>
        <td>First Name: </td><td>{{ user.first_name }}</td>
    </tr>
    <tr>
        <td>Last Name: </td><td>{{ user.last_name }}</td>
    </tr>
    <tr>
        <td>Email: </td><td>{{ user.email }}</td>
    </tr>
     <tr>
        <td>Joined: </td><td>{{ user.date_joined }}</td>
    </tr>
</table>

<br><br>

  <div>
    {% if user.is_authenticated %}
    <a href="{% url 'accounts:edit_profile' %}">EDIT PROFILE</a><br>
    <a href="{% url 'accounts:change_password' %}">CHANGE PASSWORD</a>
    {% endif %}
  </div>
<br>
  <div>
    {% if user.is_authenticated %}
    <a href="{% url 'events:add_event' %}">ADD EVENT</a>
    {% endif %}
  </div>
    {% if user.is_authenticated %}
    <a href="{% url 'events:my_events_listing' %}">MY EVENTS LISTING</a>
    {% endif %}
  </div>

  <div>
    <a href="{% url 'events:events_listing' 'all' %}">All Events listing</a>
  </div>

{% endblock content %}

explorea/templates/accounts/register.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<title>Register</title>
{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
{% endblock css %}

{% block content %}
<main>

  <div class="main-banner" id="main-banner-small">
  </div>

  <div class="login-register">
      <h2>Register</h2>

  {#  <form id='register-form' method="post" data-username-validation="{% url 'accounts:validate_username' %}">  #} <!-- konvence: custom atribut ma prefix data- -->
      <form id='register-form' method="post" data-validation="{% url 'accounts:validate_register_form' %}"> <!-- nahrazuje predchozi radek -->
<!--zmena popsana u change_password.html -->
<!--errors jsou nyni zobrazeny na zaklade input msg do ValidationError() ve validate_human_name (validators.py)  -->
<!--moznost definovat non_field_errors viz nize  -->

    {% csrf_token %}

    {% if form.non_field_errors %}
        <ul>
        {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}

    {% for field in form.visible_fields %}
        <p>{{ field.label_tag}}{{ field }}</p>
        {% for error in field.errors %}
        <div class="error">
        {{ error }}
        </div>
        {% endfor %}
    {% endfor %}

          <button type="submit" class="submit-button">Sign up</button>
      </form>



    </div>

</main>
{% endblock content %}

explorea/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block title %}
<title>Password Reset</title>
{% endblock title %}

{% block content %}
<div>

  <h2>Password Reset</h2>
  <p>Enter your email below and click "Submit". We will send you the reset link to your email immediately.</p>

  <form method="post">
    {% csrf_token %}

    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}} {{ field }}</p>

    {% endfor %}

    <button type="submit">Save</button>
  </form>

</div>
{% endblock content %}

explorea/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

explorea/templates/accounts/verification_complete.html
{% extends 'base.html' %}

{% block title %}
<title>Verification complete</title>
{% endblock title %}

{% block content %}
<p>Congratulations, you can now begin to earn your money.</p>

<p><a href="{% url 'events:add_event' %}"><strong>Add your first event</strong></a></p>
{% endblock content %}

explorea/templates/accounts/verification_sent.html
{% extends 'base.html' %}

{% block title %}
<title>Email sent</title>
{% endblock title %}

{% block content %}
<p>Time to check your email. We have sent you and email to <strong>{{ request.user.email }}</strong> with verification link. Please, click it and we are done</p>

<p>You can close this tab if your want</p>
{% endblock content %}