config/urls.py
from django.contrib import admin
from django.urls import path, include

from explorea.events import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.index, name='index'), # path vraci objekt URLPattern <URLPattern "..nejaky regularni vyraz.." [name=".."]>
    path('', views.IndexView.as_view(), name='index'),
    path('events/', include('explorea.events.urls', namespace="events")), #nyni muzeme v templatech referencovat url jako {% url "namespace:name" "var"%}, takze ruzne aplikace mohou mit stejne name (myapp/urls.py path(...,name=...))
    path('accounts/', include('explorea.accounts.urls', namespace="accounts")),
    path('cart/', include('explorea.cart.urls', namespace='cart')),
    path('posts/', include('explorea.posts.urls', namespace='posts')),
]


if settings.DEBUG: # pokud je pouzit testovaci Django server - pri ostrem provozu se pouziva k obsluhovani images separatni nezavisly server
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # static funkce spoji obe casti cesty v jeden celek (vraci list objektu URLPattern <URLPattern "..nejaky regularni vyraz.."> )

explorea/accounts/urls.py
from django.urls import path
from django.conf.urls import url

from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts' #to se propoji s config.urls kde je definovan namespace=...

urlpatterns = [
    #path('profile/', views.profile, name='profile'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    #path('login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    #path('logout/', auth_views.LogoutView.as_view(template_name="accounts/logged_out.html"), name='logout')
    path('logout/', auth_views.LogoutView.as_view(next_page="/events/all/"), name='logout'),
    #path('register/', views.register, name='register'),
    path('register/', views.RegisterView.as_view(), name='register'),
    #path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),

    #path('hosts/', views.host_list, name='host_list'),
    path('hosts/', views.HostListView.as_view(), name='host_list'),
    #path('become-host/', views.become_host, name='become_host'),
    path('become-host/', views.BecomeHostView.as_view(), name='become_host'),
    #path('host/profile/<username>/', views.host_profile, name='host_profile'),
    path('host/profile/<username>/', views.HostProfileView.as_view(), name='host_profile'),
    #url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.activate_host, name='activate_host'),
    url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.ActivateHostView.as_view(), name='activate_host'),

    # <uidb64> a <token> se zparsuji do views.activate_host jako kwargs;
    # ?P<uidb64> je Python named capture group (<uidb64> je refernece na [0-9A-Za-z]+, muze byt backreferencovana jako (?P=uidb64)), . = libovolny znak

    #path('change-password/', views.change_password, name='change_password'),
    path('change-password/', views.PasswordChangeView.as_view(), name='change_password'),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name = 'accounts/reset_password.html', email_template_name='accounts/reset_password_email.html'),
        name='reset_password'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    # path('ajax/validate_username/', views.ValidateUsernameView.as_view(), name='validate_username'),
    path('ajax/validate_exists/', views.ValidateRegisterFormView.as_view(), name='validate_register_form'), # nahrazuje predchozi path

    ]

explorea/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='detail'),
    path('add/<slug:slug>/', views.CartAddView.as_view(), name='add'),
    #path('remove/<product_id>/', views.CartRemoveView.as_view(), name='remove'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),

]

explorea/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    #path('new/', views.add_event, name='add_event'),
    path('new/', views.AddEventView.as_view(), name='add_event'),
    #path('mine/', views.my_events_listing, name='my_events_listing'),
    path('mine/', views.MyEventsView.as_view(), name='my_events_listing'),
    #path('search/', views.event_search, name='search'),
    path('search/', views.EventSearchView.as_view(), name='search'),

    #path('detail/<slug:slug>/', views.event_detail, name='event_detail'),#slug je samostatny type (jako str nebo int)
    path('detail/<slug:slug>/', views.EventDetailView.as_view(), name='event_detail'),
    #path('update/<slug:slug>/', views.update_event, name='update_event'),#chybejici lomitko na konci nesmyslne spousti nasledujici pattern!
    path('update/<slug:slug>/', views.UpdateEventView.as_view(), name='update_event'),
    #path('delete/<slug:slug>/', views.delete_event, name='delete_event'),
    path('delete/<slug:slug>/', views.DeleteEventView.as_view(), name='delete_event'),

    #path('<slug:slug>/update_run/<str:run_id>/', views.update_run, name='update_run'),
    path('<slug:slug>/update_run/<str:run_id>/', views.UpdateEventRunView.as_view(), name='update_run'),
    #path('<slug:slug>/delete_run/<str:run_id>/', views.delete_run, name='delete_run'),
    path('<slug:slug>/delete_run/<str:run_id>/', views.DeleteEventRunView.as_view(), name='delete_run'),
    #path('<slug:slug>/add_run/', views.add_run, name='add_run'),
    path('<slug:slug>/add_run/', views.AddEventRunView.as_view(), name='add_run'),

    #path('<str:event_id>/runs/', views.runs_listing, name='runs_listing'),
    #path('<str:event_id>/<str:run_id>/', views.run_detail, name='run_detail'),

    #path('<category>/', views.events_listing, name='events_listing'),
    path('<category>/', views.EventListView.as_view(), name='events_listing'),

]

explorea/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('<slug:slug>/add_rating/', views.AddRatingView.as_view(), name='add_rating'),
    path('<slug:slug>/ratings/', views.RatingListView.as_view(), name='ratings_listing'),
]

explorea/cart/models.py
from django.db import models

# Create your models here.

explorea/posts/forms.py
from django import forms

from explorea.events.models import EventRun
from . models import Rating

from django.forms import ModelChoiceField

class MyModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return str(obj.date) + " " + str(obj.time)

class AddRatingForm(forms.ModelForm):

    # implement MyModelChoiceField
    eventrun = MyModelChoiceField(queryset = EventRun.objects.all(), empty_label=None)

    class Meta:
        model = Rating
        exclude = ["event"]

explorea/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, update_session_auth_hash, get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse

# from django.contrib.auth.mixins import LoginRequiredMixin # LoginRequiredMixin byl z dedicnosti odstranen po zavedeni custom middleware
from django.views.generic import TemplateView, DetailView, ListView, View
from django.views.generic.base import TemplateResponseMixin, ContextMixin
from django.views.generic.edit import CreateView, UpdateView, FormMixin, ProcessFormView
from django.urls import reverse_lazy

from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes

from .forms import RegisterForm, EditUserForm, EditProfileForm
from .models import Profile

UserModel = get_user_model()
token_generator = PasswordResetTokenGenerator()


# @login_required
#
# def profile(request):
#
#     return render(request, 'accounts/profile.html')


class ProfileView(TemplateView):

    template_name = 'accounts/profile.html'


# def register(request):
#
#     if request.method == 'POST':
#
#         # create the form and populate it with data from the POST request
#         form = RegisterForm(request.POST)
#
#         # validate the data in the form
#         if form.is_valid():#vytvoren atribut form.cleaned_data (type=dict) a validovana data do nej ulozena
#
#
#             # get the validated data from the form
#             username = form.cleaned_data.get('username')# nazvy poli formulare jsou ve slovniku jako "key" (type=str)
#             email = form.cleaned_data.get('email')
#             first_name = form.cleaned_data.get('first_name')
#             last_name = form.cleaned_data.get('last_name')
#             password = form.cleaned_data.get('password1')
#
#             # create and save the user
#             User = get_user_model() # ziska referenci k nami zvolenemu user modelu (settings.AUTH_USER_MODEL, nachazi se v general_settings.py a Djanguv defaultni je auth.User)
#             u = User(username=username,
#                      email=email,
#                      first_name=first_name,
#                      last_name=last_name)
#             u.set_password(password)#pouze tato metoda ulozi password hash
#             u.save()
#
#             # get the validated data from the form, create and save the user
#             user=form.save()# protoze implementujeme RegisterForm jako ModelForm--> lze pouzit save --> vrati user object jako radek, ktery zapise do databaze
#             raw_password = form.cleaned_data.get('password1')
#
#             #user = authenticate(username=username, password=password) #vyhleda username v databazi, zahashuje argument password a porovna s odpovidajicim v databazi, vrati objekt user
#             user = authenticate(username=user.username, password=raw_password)
#             login(request, user) #vytvori user session
#
#             # redirect to another page
#             return redirect('accounts:profile')#parametrem je view, ktery chceme spustit, Django default - settings.LOGIN_REDIRECT_URL (="/accounts/profile")
#
#         else: # form.is_valid() vrati False, viz def change_password
#             return render(request, 'accounts/register.html', {'form': form} )
#
#     # if the request is of type GET
#     form = RegisterForm()
#     return render(request, 'accounts/register.html', {'form': form} )


class RegisterView (CreateView):
    model = UserModel
    form_class = RegisterForm
    template_name = 'accounts/register.html'

    #success_message = 'The user %(username)s has been registered successfully' # property pouzivane MessageActionMixin metodami
    #error_message = 'The user %(username)s can not be registered'

    def form_valid(self, form):
        user = form.save()
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=user.username, password=raw_password)
        login(self.request, user)

        #super().form_valid(form)

        return redirect('accounts:profile')


# @login_required
# def edit_profile(request):
#
#     user_form = EditUserForm(request.POST or None, instance=request.user) #  pokud request.method == 'GET': request.POST je <QueryDict {}>, pokud request.method == 'POST': request.POST je <QueryDict {"csrfmiddlewaretoken": ["..."], "username":["Michal"], ..., "about":["neco"]}>
#     profile_form = EditProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)#instance urcuje jaka data maji byt ve formulari predvyplnena # musi byt dodrzene poradi requestu text, files
#                                                                                                             #  pokud request.method == 'POST', request.POST nyni obsahuje field: "avatar":["nazev_obrazku.png"]
#     if request.method == 'POST':
#
#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()
#             profile = profile_form.save()
#
#             request.session['profile_changes'] = request.session.setdefault('profile_changes', 0) + 1#do request.session objektu (lze s nim pracovat jako se slovnikem) se ulozi pod klicem profile_changes defautni hodnota 0,
#                                                                                    #ktera se pri kazdem ulozeni formulare do databaze ve views.edit_profile zvysi o 1
#             return redirect('accounts:profile')
#
#     return render(request, 'accounts/edit_profile.html',
#         {'user_form': user_form, 'profile_form': profile_form})


class MultipleFormsMixin (ContextMixin):
    forms_classes = {}
    initial = {}
    success_url = "" # atributy budou overridovany view, ktere z mixinu dedi

    def get_forms_classes (self):

        return self.forms_classes.copy() # copy() - puvodni dict forms_classes zustane nezmenen v pripade, ze se zmeni novy dict (ktery vraci get_forms_classes()), jinak by se pripadne zmeny dotkly obou
                                        # vezme to, co je definovano v EditProfileView.forms_classes a pokracuje v MFM.get_forms(): forms = self.get_forms_classes()
    def get_context_data(self, **kwargs):

        if 'forms' not in kwargs:
            forms = self.get_forms() # GET: forms = {'user_form': <EditUserForm bound=False, valid=Unknown, fields=(username;email;first_name;last_name;password)>, 'profile_form': <EditProfileForm bound=False, valid=Unknown, fields=(about;avatar)>}

            for name, form in forms.items():
                kwargs[name] = form # ulozi napr. kwargs["user_form"]= <EditUserForm bound=False, valid=Unknown, fields=(username;email;first_name;last_name;password)>
                                    # ve vysledku kwargs==forms

            return super().get_context_data(**kwargs) # ContextMixin.get_context_data()


#        else:
#            keys = ("user_form", "profile_form")
#            for index,value in enumerate(kwargs["forms"]):
#                kwargs[keys[index]]=value
#            kwargs.pop ("forms")


    def get_forms_kwargs(self):
        kwargs = {}
        for name, form in self.forms_classes.items():
            kwargs[name] = {"initial": self.get_initial(),}
            if self.request.method in ('POST', 'PUT'):
                kwargs[name].update({'data': self.request.POST, 'files': self.request.FILES,})

        return kwargs

    def get_forms(self, forms_classes = None):
        if forms_classes is None:
            forms = self.get_forms_classes() # GET, POST: forms = {'user_form': <class 'explorea.accounts.forms.EditUserForm'>, 'profile_form': <class 'explorea.accounts.forms.EditProfileForm'>}

        kwargs = self.get_forms_kwargs() # GET: kwargs = {'user_form': {'initial': {}, 'instance': <SimpleLazyObject: <User: ab>>}, 'profile_form': {'initial': {}, 'instance': <Profile: Profile object (1)>}}
                                        # POST: kwargs = {'user_form': {'initial': {}, 'data': <QueryDict: {'csrfmiddlewaretoken': ['..'], 'username': ['ab'], 'email': ['a@b.cz'], 'first_name': ['Acko'], 'last_name': ['Becko'], 'about': ['dwdwd']}>, 'files': <MultiValueDict: {'avatar': [<InMemoryUploadedFile: ..>]}>, 'instance': <SimpleLazyObject: <User: ab>>},
                                        #              'profile_form': {'initial': {}, 'data': <QueryDict: {'csrfmiddlewaretoken': ['..'], 'username': ['ab'], 'email': ['a@b.cz'], 'first_name': ['Acko'], 'last_name': ['Becko'], 'about': ['dwdwd']}>, 'files': <MultiValueDict: {'avatar': [<InMemoryUploadedFile: ..>]}>, 'instance': <Profile: Profile object (1)>}}
                                        # odkazuje na EditProfileView.get_forms_kwargs()

        return {name:form(**kwargs[name]) for name, form in forms.items()} # dict.items() vraci [("key", value), ("key", value), ... ], **dict - rozbali pary key:value jako kwargs (var=value) pri volani funkce
                                                                        # napr. pro 'user_form' vraci:
                                                                        #    GET: forms['user_form'](**kwargs['user_form']) --> <EditUserForm bound=False, valid=Unknown, fields=(username;email;first_name;last_name;password)>

explorea/templates/events/add_event.html
{% extends 'base.html' %}

{% block title %}
<title>Add your event</title>
{% endblock title %}

{% block content %}

<div>
  <a href="{% url 'accounts:profile' %}">{{ user.get_full_name }}</a>
</div>

<div>

  <h2>Add Event {{ event.name }}</h2>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form.visible_fields %}

        <p>{{ field.label_tag}}{{ field }}</p>

        {% for error in field.errors %}
          {{ error }}
        {% endfor %}

    {% endfor %}

    <button type="submit">Save</button>
  </form>

</div>
{% endblock content %}

explorea/templates/events/add_run.html
{% extends 'base.html' %}

{% block title %}
<title>Add event run</title>
{% endblock title %}

{% block content %}

<div>
  <a href="{% url 'accounts:profile' %}">{{ user.get_full_name }}</a>
</div>

<div>

  <h2>Add event run</h2>

  <form method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}}{{ field }}{{ field.help_text }}</p>

    {% endfor %}
    <button type="submit">Save</button>
  </form>

</div>
{% endblock content %}

explorea/templates/events/event_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit">Delete</button>
    <a class="button-gold " href="{{ object.get_absolute_url }}">Cancel</a>
</form>

{% endblock %}

explorea/templates/events/event_detail.html
{% extends 'base.html' %}

{% load event_tags %}
{% load cart_tags %}

{% block title %}
<title>Event Detail</title>
{% endblock title %}

{% block content %}
<main>

  <h1>{{ event.name }}
    {#  {% if event.host == user %}  #} <!-- pouze user, ktery vytvoril event, ho muze editovat --> <!-- event.host is user: nefunguje, protoze user (z requestu) je SimpleLazyObject -->
      <h3>
    | <a class="edit-button" href="{% url 'events:update_event' event.slug %}">UPDATE THIS EVENT</a>  <!-- h1 a h3  - display: inline v css, aby byly vedle sebe   -->
    | <a class="edit-button" href="{% url 'events:delete_event' event.slug %}">DELETE THIS EVENT</a>
      </h3>
    {#  {% endif %}  #}
  </h1>

      <ul>
        <li>HOST: {{ event.host.get_full_name }}
        <li>LOCATION: {{ event.location}}
        <li>DESCRIPTION: {{ event.description}}
      </ul>

      <br>

      <div class="rating">
        <p>AVERAGE RATING: {{ avg_rating }} | NUMBER OF RATINGS: {{ num_ratings }} | <a class="edit-button" href="{% url 'posts:add_rating' event.slug %}">RATE THIS EVENT</a></p>
        <p><a class="edit-button" href="{% url 'posts:ratings_listing' event.slug %}">SHOW RATINGS OF THIS EVENT</a><p>
      </div>

      <div class="main-image">
        {% if event|has:'main_image' %}
        <img src="{{ event.main_image.url }}">
        {% else %}
        <div class="not-available">
          <i class="far fa-calendar-alt" id="event-item-icon"></i>
        </div>
        {% endif %}
      </div>

      <!--Image slideshow-->
      <div class="owl-carousel">
        {% for image in event.album.image_set.all %}
        <img src="{{ image.image.url }}" alt="{{ image.title }}"> <!--alt...alternativni popis - libovolny text-->
        {% endfor %}
      </div>

  <h1>Availability</h1>
<br>
  <ul>
  {% for run in runs %} <!-- |active -->
  <li>DATE: {{ run.date }},&nbsp; {{ run.time }},&nbsp; {{ run.seats_available }},&nbsp; {{ run.price }}

  {#  {% if run.event.host == user %}  #}

    &nbsp <a class="edit-button" href="{% url 'events:update_run' run.event.slug run.id %}">UPDATE THIS RUN</a>
    &nbsp <a class="edit-button" href="{% url 'events:delete_run' run.event.slug run.id %}">DELETE THIS RUN</a>
  {#  {% else %}  #}
    <td>
      <div>
        <form class='cart-add' method='POST' action="{% url 'cart:add' run.event.slug %}"> <!-- class='cart-add' nadefinujeme, protoze pouzivame v testech k vyberu elementu -->
                                                                                            <!-- form action=.. po stlaceni submit presmerovava na zadane url -->
          {% csrf_token %}
          {{ cart_add_form.quantity }}
          {# {{ cart_add_form.current_quantity }} #}   <!-- toto je typ commentu, ktery nikdy nespusti obsazeny kod! nesmi byt multiline  -->
          <input name="current_quantity" value="{% get_key cart run.id %}" type="hidden"> <!-- run.id je product_id  -->
          <input name="product_id" value={{ run.id }} type="hidden">
          <button type='submit'>Add to Cart</button>
        </form>
      </div>
    </td>
  {#  {% endif %}  #}

    <br>

  {#     {% if run.event.host == user %}  #}
    <div><a href="{% url 'events:add_run' event.slug %}">ADD EVENT RUN</a></div>
  {#         {% endif %}   #}

  {% endfor %}

  </ul>

<div><a href="{% url 'events:my_events_listing' %}">BACK</a></div>

</main>
{% endblock content %}

explorea/templates/events/eventrun_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete event run <strong> {{ object.date }} </strong> for event <strong> {{ object.event.name }} </strong> ?</p>
    <button type="submit">Delete</button>
    <a class="button-gold " href="{{ object.event.get_absolute_url }}">Cancel</a>
</form>

{% endblock %}

explorea/templates/events/events_listing.html
{% extends 'base.html' %}

{% load event_tags %}   <!--nacte custom filtry z events/templatetags/event_tags.py, templatetags je package-->
{% load static %}

{% block title %}
<title>Event Listing</title>
{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/events_listing.css' %}">
{% endblock css %}

{% block content %}
<main>
  <div class="events-banner">

    <h1>Events Listing</h1>

  </div>

  <form class="event-filters"  method="GET">
      {% for hidden_field in form.hidden_fields %}
          {{ hidden_field }}
      {% endfor %}

      {% for field in filter_form.visible_fields %}
          <div class="form-filter">
              {{ field.label_tag }} {{ field }} <!--pokud je form method = GET, <input type="neco" name="guests"...> znamena ze request.GET bude obsahovat pod key guests uzivatelem vlozenou hodnotu do pole input -->
          </div>

              <div class="errors" for={{ field.name }}> <!--for je atribut,{{ field.name }} je value - diky tomu v css: napriklad .errors[for="date_to"]   -->
                  {% for error in field.errors %}
                      <div class="error">{{ error }}</div>
                  {% endfor %}
              </div>

      {% endfor %}
      <button class="submit-button" type="submit">Filter</button>
  </form>

  <div class="event-category-filters">
      <!--by clicking these buttons we should be taken to event listing, that show us only events of the given event category-->
      <a class="sort-button" href="{% url 'events:events_listing' 'fun' %}">Fun</a>
      <a class="sort-button" href="{% url 'events:events_listing' 'experience' %}">Experience</a>
      <a class="sort-button" href="{% url 'events:events_listing' 'sights' %}">Sights</a>
      <a class="sort-button" href="{% url 'events:events_listing' 'relax' %}">Relax</a>
      <a class="sort-button" href="{% url 'events:events_listing' 'all' %}">All</a>
  </div>

  <div class="events-container">
    {% if event_runs %}
      {% for eventrun in event_runs %}
          <a class="event-item" href="{{ eventrun.event.get_absolute_url }}">
            {% if eventrun.event|has:'thumbnail' %}
                <img src="{{ eventrun.event.thumbnail.url }}">
            {% else %}
                <div class="not-available"></div>
                  <i class="far fa-calendar-alt" id="event-item-icon"></i>
            {% endif %}
                <div class="event-item-details">
                    <p>HOST: {{ eventrun.event.host }} </p>
                    <p>{{ eventrun.event.name }}</p> <!-- <br> vytvori 1 prazdny radek -->
                    <p>{{ eventrun.event.location}}</p> <!--events:event_detail je namespace:name,  event.name se vlozi do <...> u odpovidajici funkce path, kde name="event_detail"-->
                    <p><strong>Next:</strong> {{ eventrun.date}} </p><!--event.eventrun_set.all je queryset(odpovida objects), min_attr_value je custom filter funkce, "date" je argument teto funkce (odpovida field_name) -->
                    <p><strong>Price:</strong> {{ eventrun.price }}</p>
                    <p><strong>Seats:</strong> {{ eventrun.seats_available }}</p>
                    <hr>
                    <p><strong>From:</strong> {{ eventrun.event.eventrun_set.all|active|min_attr_value:"price" }}</p><!-- filtry lze radit za sebou; events je napr. <EventQuerySet[<Event: Sitting>]>, event je <Event: Sitting>, tzn. objekt -->
                    <p><strong>Seats Up To:</strong> {{ eventrun.event.eventrun_set.all|active|max_attr_value:"seats_available" }}</p>
                </div>
          </a>
      {% endfor %}
    {% else %}
      <div class="info empty-search">No events found ...</div>
    {% endif %}
  </div>

</main>
{% include 'pagination.html' with page=page_obj %}    <!--event_runs, ktere nam vraci views.py/event_listing -> zmena: page_obj, ktere nam vraci views.py/vse co dedi z ListView  se budou v template pagination.html nazyvat page-->

{% endblock content %}

explorea/templates/events/index.html
{% extends 'base.html' %}

{% block title %}
<title>Home Page</title>
{% endblock title %}

{% block content %}

<div class="main-banner">  <!-- zde je umisten background image -->
    <p class="claim">Let's do something</p>
    <a class="sort-button" href="{% url 'events:events_listing' 'fun' %}">Fun</a>
    <a class="sort-button" href="{% url 'events:events_listing' 'experience' %}">Experience</a>
    <a class="sort-button" href="{% url 'events:events_listing' 'sights' %}">Sights</a>
    <a class="sort-button" href="{% url 'events:events_listing' 'relax' %}">Relax</a>
</div>


{% endblock content %}

explorea/templates/events/my_events_listing.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<title> Your Events Listing</title>
{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/events_listing.css' %}">
{% endblock css %}

{% block content %}
<main>
  <div class="events-banner">

    <h1>Your Events Listing</h1>

  </div>

    <ul class="events-container">
    {% for event in events %}
      <li class="event-item">
        <i class="far fa-calendar-alt" id="event-item-icon"></i>

        <p>HOST: {{ event.host }} </p>
        <p><a href="{% url 'events:event_detail' event.slug %}">{{ event.name }}</a> </p> <!-- <br> vytvori 1 prazdny radek -->
        <p>{{ event.location}}</p> <!--events:event_detail je namespace:name,  event.name se vlozi do <...> u odpovidajici funkce path, kde name="detail"-->
        <p><a href="{% url 'events:update_event' event.slug %}">UPDATE</a></p>
        <p><a href="{% url 'events:delete_event' event.slug %}">DELETE</a></p>
    {% endfor %}
    </ul>


</main>
{% endblock content %}